#!/usr/bin/env ruby

begin
  require 'phileas'
rescue LoadError
  require 'rubygems'
  require 'phileas'
end

if File.expand_path(__FILE__) == File.expand_path($0)
  # make sure simulator config file exists
  unless ARGV.size >= 1 
    do_abort("No simulator configuration file given!")
  end

  unless File.exists?(ARGV[0])
    do_abort("File #{ARGV[0]} does not exist!")
  end

  # load simulation configuration
  conf = Phileas::Configuration.load_from_file(ARGV[0])

  # create a simulator and launch it
  sim = Phileas::Simulator.new(configuration: conf)
  sim.run
end
